[project]
name = 'athletic-performance-data-marketplace'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.data-licensing]
path = 'contracts/data-licensing.clar'
clarity_version = 2
epoch = 2.5

[contracts.performance-nft]
path = 'contracts/performance-nft.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
